/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import FachadaConsultarPedido.FachadaConsulta;
import ISAT.ISAT;
import InterfaceConsultarPedido.IConsultaPedido;
import InterfaceFinanza.IFinanza;
import com.mycompany.dto.ClienteDTO;
import com.mycompany.dto.FacturaDTO;
import com.mycompany.pasteleriabo.SATBO;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author cesar
 */
public class DatosFactura extends javax.swing.JFrame {

      private int pedidoId;
    private IConsultaPedido consulta;
    private JTable tablaClientes;
    private IFinanza fachadaFinanza;
    private ISAT fachadaSAT;

    public DatosFactura(int pedidoId) {
        this.pedidoId = pedidoId;
        this.consulta = new FachadaConsulta(); // Inicializar la fachada
        initComponents();
        inicializarValores();
        setLocationRelativeTo(null);

    }

    private void inicializarValores() {
         // Consultar cliente por pedidoId
           String pedidoIdStr = String.valueOf(pedidoId);
          // Consultar cliente por pedidoId
    ClienteDTO cliente = consulta.obtenerClientePorPedidoId(pedidoIdStr);
    
    if (cliente != null) {
        nombreLabel.setText(cliente.getNombre());
        apellidoLabel.setText(cliente.getApellido());
    } else {
        nombreLabel.setText("N/A");
        apellidoLabel.setText("N/A");
    }

    jLabel4.setText(String.valueOf(pedidoId));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rfcField = new javax.swing.JTextField();
        usoFiscalField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        curpField = new javax.swing.JTextField();
        nombreLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        apellidoLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(247, 239, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("SAT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Datos Factura");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        jLabel3.setText("No.Pedido:");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 70, 30));

        jLabel4.setText("numeroPedido");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("RFC:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel6.setText("Nombre :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel7.setText("Uso Fiscal:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        rfcField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rfcFieldActionPerformed(evt);
            }
        });
        jPanel2.add(rfcField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 250, -1));

        usoFiscalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usoFiscalFieldActionPerformed(evt);
            }
        });
        jPanel2.add(usoFiscalField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 210, 20));

        jLabel8.setText("CURP:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));
        jPanel2.add(curpField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 230, 20));

        nombreLabel.setText("Nombre ");
        jPanel2.add(nombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 100, 20));

        jLabel9.setText("Apellido:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        apellidoLabel.setText("jLabel10");
        jPanel2.add(apellidoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 90, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 300, 170));

        jButton1.setBackground(new java.awt.Color(255, 0, 204));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rfcFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rfcFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rfcFieldActionPerformed

    private void usoFiscalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usoFiscalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usoFiscalFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Validar que los campos no estén vacíos
        if (rfcField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo RFC no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (usoFiscalField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo Uso Fiscal no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (curpField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo CURP no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Si todos los campos están llenos, proceder a crear el objeto FacturaDTO
        FacturaDTO facturaDTO = new FacturaDTO();
        facturaDTO.setRFC(rfcField.getText());
        facturaDTO.setUsoFiscal(usoFiscalField.getText());
        facturaDTO.setCURP(curpField.getText());
        facturaDTO.setPedidoId(pedidoId);
//   facturaDTO.setId(clienteDTO.getId());

        // Enviar los datos a la capa de negocio
        SATBO facturaBO = new SATBO();
        facturaBO.agregarDatosFactura(facturaDTO);

        // Abrir la ventana FacturaSAT y cerrar la actual
        FacturaSAT fac = new FacturaSAT(pedidoId);
        fac.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidoLabel;
    private javax.swing.JTextField curpField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField rfcField;
    private javax.swing.JTextField usoFiscalField;
    // End of variables declaration//GEN-END:variables
}
