/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import FachadaSAT.FachadaSAT;
import ISAT.ISAT;
import com.mycompany.dto.ClienteDTO;
import com.mycompany.dto.FacturaDTO;
import com.mycompany.dto.PedidoDTO;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author cesar
 */
public class FacturaSAT extends javax.swing.JFrame {

    private int pedidoId;
    private ISAT subsistemaSAT;
    private String fechaActual;

    /**
     * Creates new form FacturaSAT
     */
    public FacturaSAT(int pedidoId) {
        this.pedidoId = pedidoId;
        this.subsistemaSAT = new FachadaSAT(); // Inicializar la fachada
        this.fechaActual = LocalDate.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")); // Obtener la fecha actual

        initComponents();
        inicializarValores();
        setLocationRelativeTo(null);
    }

    private void inicializarValores() {
        // Obtener datos del pedido
        PedidoDTO pedido = subsistemaSAT.obtenerPedidoPorId(pedidoId);
        if (pedido != null) {
            jLabelPedidoId.setText(String.valueOf(pedido.getPedidoid()));
            int precioTotal = pedido.getPrecioTotal();
            jLabelPrecioTotal.setText(String.valueOf(precioTotal));
            // Obtener datos del cliente
            ClienteDTO cliente = subsistemaSAT.obtenerClientePorId(pedido.getClienteId());
            System.out.println(cliente.toString());
            if (cliente != null) {
                jLabelNombre.setText(cliente.getNombre());
                jLabelApellido.setText(cliente.getApellido());
                jLabelCorreo.setText(cliente.getCorreo());
            }

            // Obtener datos de la factura
            FacturaDTO factura = subsistemaSAT.obtenerFacturaPorPedidoId(pedidoId);
            if (factura != null) {
                jLabelRFC.setText(factura.getRFC());
                jLabelUsoFiscal.setText(factura.getUsoFiscal());
                jLabelCURP.setText(factura.getCURP());
            }
            jLabelFechaActual.setText(fechaActual);
            LocalDate fechaActual = LocalDate.now();
            LocalDate fechaVencimiento = fechaActual.plusMonths(1);
            String fechaVencimientoStr = fechaVencimiento.toString();
            FechaVencimiento.setText(fechaVencimientoStr);
            Random random = new Random();
            int numeroFactura = random.nextInt(1000) + 1; // Random number between 1 and 1000
            numeroFac.setText(Integer.toString(numeroFactura));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        numeroFac = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelFechaActual = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelPedidoId = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        FechaVencimiento = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabelPrecioTotal = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabelApellido = new javax.swing.JLabel();
        jLabelCorreo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelRFC = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelUsoFiscal = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabelCURP = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("No.Factura:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        numeroFac.setText("numeroFactura");
        jPanel1.add(numeroFac, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Factura a nombre de:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabelNombre.setText("nombre");
        jPanel1.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Fecha:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabelFechaActual.setText("Fecha");
        jPanel1.add(jLabelFechaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("No.Pedido:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        jLabelPedidoId.setText("numeroPedido");
        jPanel1.add(jLabelPedidoId, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Fecha Vencimiento:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        FechaVencimiento.setText("FechaVencimiento");
        jPanel1.add(FechaVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Precio:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabelPrecioTotal.setText("precio");
        jPanel1.add(jLabelPrecioTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLabel18.setText("FACTURA DIGITAL");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, -1, -1));

        jButton2.setText("MENU");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 140, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Presentación1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 80));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/codigoqr.png"))); // NOI18N
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, -1, -1));

        jLabelApellido.setText("apellido");
        jPanel1.add(jLabelApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        jLabelCorreo.setText("jLabel5");
        jPanel1.add(jLabelCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Correo Electronico:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        jLabelRFC.setText("jLabel9");
        jPanel1.add(jLabelRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("RFC:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabelUsoFiscal.setText("jLabel15");
        jPanel1.add(jLabelUsoFiscal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("UsoFiscal:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabelCURP.setText("jLabel12");
        jPanel1.add(jLabelCURP, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("CURP:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FechaVencimiento;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelCURP;
    private javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelFechaActual;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPedidoId;
    private javax.swing.JLabel jLabelPrecioTotal;
    private javax.swing.JLabel jLabelRFC;
    private javax.swing.JLabel jLabelUsoFiscal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel numeroFac;
    // End of variables declaration//GEN-END:variables
}
